#!/usr/bin/env python3
# Compiles the shaders in this directory to SPIR-V (needs glslc from the Vulkan SDK) and writes ../vk_spirv.h.
# The generated header is checked in, so a build does not need glslc; run this after changing a shader.
import os, re, struct, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
out = ["// Generated by shaders/build.py from shaders/*.vert and shaders/*.frag. Do not edit.\n",
       "// The smaa_*.frag shaders contain SMAA by Jorge Jimenez et al. (MIT license, copyright notice in\n",
       "// rd-vanilla/tr_smaa_data.h, which asks that it goes with copies; it is not required for binary distributions).\n",
       "#pragma once\n\n"]

def smaa_source():
    # the SMAA code (MIT license, see the notice at the top of tr_smaa_data.h) is kept in the C++ header of the OpenGL
    # renderer as raw string literals
    text = open(os.path.join(here, "..", "..", "rd-vanilla", "tr_smaa_data.h")).read()
    block = text[text.index("smaaShaderSource[]"):]
    block = block[:block.index("\n};")]
    return "".join(re.findall(r'R"SMAA\((.*?)\)SMAA"', block, re.S))

SMAA_HEAD = "#version 450\n#define SMAA_GLSL_4 1\n#define SMAA_PRESET_HIGH 1\n"
SMAA_PUSH = "layout(push_constant) uniform P { vec4 a; } p;\n#define SMAA_RT_METRICS p.a\n"
SMAA_MAINS = {
    "smaa_edges.frag": "layout(set = 0, binding = 0) uniform sampler2D uColor;\n"
        "layout(location = 0) in vec2 vUV;\nlayout(location = 0) out vec4 outColor;\n"
        "void main() { vec4 offset[3]; SMAAEdgeDetectionVS(vUV, offset);\n"
        "outColor = vec4(SMAALumaEdgeDetectionPS(vUV, offset, uColor), 0.0, 0.0); }\n",
    "smaa_weights.frag": "layout(set = 0, binding = 0) uniform sampler2D uEdges;\n"
        "layout(set = 0, binding = 1) uniform sampler2D uArea;\nlayout(set = 0, binding = 2) uniform sampler2D uSearch;\n"
        "layout(location = 0) in vec2 vUV;\nlayout(location = 0) out vec4 outColor;\n"
        "void main() { vec2 pixcoord; vec4 offset[3]; SMAABlendingWeightCalculationVS(vUV, pixcoord, offset);\n"
        "outColor = SMAABlendingWeightCalculationPS(vUV, pixcoord, offset, uEdges, uArea, uSearch, vec4(0.0)); }\n",
    "smaa_blend.frag": "layout(set = 0, binding = 0) uniform sampler2D uColor;\n"
        "layout(set = 0, binding = 1) uniform sampler2D uBlend;\n"
        "layout(location = 0) in vec2 vUV;\nlayout(location = 0) out vec4 outColor;\n"
        "void main() { vec4 offset; SMAANeighborhoodBlendingVS(vUV, offset);\n"
        "outColor = SMAANeighborhoodBlendingPS(vUV, offset, uColor, uBlend); }\n",
}

shaders = [("fixed.vert", "vert"), ("fixed.frag", "frag"), ("dlight.vert", "vert"), ("dlight.frag", "frag"),
           ("post.vert", "vert"), ("post_ssao.frag", "frag"), ("post_ssao_blur.frag", "frag"),
           ("post_bloom_down.frag", "frag"), ("post_bloom_up.frag", "frag"), ("post_composite.frag", "frag")]
shaders += [(n, "frag") for n in SMAA_MAINS]

for name, stage in shaders:
    if name in SMAA_MAINS:
        source = SMAA_HEAD + SMAA_PUSH + smaa_source() + SMAA_MAINS[name]
        spv = subprocess.run(["glslc", "-O", "-fshader-stage=frag", "-x", "glsl", "-o", "-", "-"],
                             input=source.encode(), check=True, stdout=subprocess.PIPE).stdout
    else:
        spv = subprocess.run(["glslc", "-O", "-fshader-stage=" + stage, "-o", "-", os.path.join(here, name)],
                             check=True, stdout=subprocess.PIPE).stdout
    words = struct.unpack("<%dI" % (len(spv) // 4), spv)
    ident = "vk_spirv_" + name.replace(".", "_")
    out.append("static const unsigned int %s[%d] = {\n" % (ident, len(words)))
    for i in range(0, len(words), 8):
        out.append("\t" + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",\n")
    out.append("};\n\n")
open(os.path.join(here, "..", "vk_spirv.h"), "w").write("".join(out))
print("wrote vk_spirv.h")
