#!/usr/bin/env python3
# Compiles the shaders in this directory to SPIR-V (needs glslc from the Vulkan SDK) and writes ../vk_spirv.h.
# The generated header is checked in, so a build does not need glslc; run this after changing a shader.
import os, struct, subprocess, sys

here = os.path.dirname(os.path.abspath(__file__))
out = ["// Generated by shaders/build.py from shaders/*.vert and shaders/*.frag. Do not edit.\n", "#pragma once\n\n"]
for name, stage in (("fixed.vert", "vert"), ("fixed.frag", "frag")):
    spv = subprocess.run(["glslc", "-O", "-fshader-stage=" + stage, "-o", "-", os.path.join(here, name)],
                         check=True, stdout=subprocess.PIPE).stdout
    words = struct.unpack("<%dI" % (len(spv) // 4), spv)
    ident = "vk_spirv_" + name.replace(".", "_")
    out.append("static const unsigned int %s[%d] = {\n" % (ident, len(words)))
    for i in range(0, len(words), 8):
        out.append("\t" + ", ".join("0x%08x" % w for w in words[i:i + 8]) + ",\n")
    out.append("};\n\n")
open(os.path.join(here, "..", "vk_spirv.h"), "w").write("".join(out))
print("wrote vk_spirv.h")
