#!/usr/bin/env python3
# Generates code/client/snd_hrtf_data.cpp from the MIT KEMAR "diffuse" head-related impulse responses.
#
#   usage: gen_hrtf_data.py <dir with the unpacked diffuse.zip (elev-40 .. elev90)> <output .cpp>
#
# Source: https://sound.media.mit.edu/resources/KEMAR.html (diffuse.zip, 44.1kHz, 128 samples)
# "This data is Copyright 1994 by the MIT Media Laboratory. It is provided free with no restrictions
#  on use, provided the authors are cited when the data is used in any research or commercial
#  application." - Bill Gardner and Keith Martin, MIT Media Lab Machine Listening Group.
#
# This script is original code released under the same terms as the rest of OpenJK (GPL version 2).
import glob, re, struct, sys, wave

def load(path):
	w = wave.open(path)
	assert w.getnchannels() == 2 and w.getsampwidth() == 2 and w.getframerate() == 44100 and w.getnframes() == 128, path
	d = struct.unpack('<%dh' % (w.getnframes() * 2), w.readframes(w.getnframes()))
	return d[0::2], d[1::2]		# channel 0 = left ear, channel 1 = right ear, for a source on the right (positive azimuth)

def main():
	src, out = sys.argv[1], sys.argv[2]
	rings = {}
	for f in glob.glob(src + '/elev*/H*.wav'):
		m = re.search(r'elev(-?\d+)/H(-?\d+)e(\d+)a\.wav$', f)
		rings.setdefault(int(m.group(1)), []).append((int(m.group(3)), f))
	elevs = sorted(rings)
	o = []
	o.append('''/*
===========================================================================
Copyright (C) 2013 - 2015, OpenJK contributors

This file is part of the OpenJK source code.

OpenJK is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License version 2 as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, see <http://www.gnu.org/licenses/>.
===========================================================================
*/

// snd_hrtf_data.cpp -- head-related impulse responses for snd_hrtf.cpp
//
// GENERATED by tools/hrtf/gen_hrtf_data.py, do not edit by hand.
//
// The measurements are the diffuse-field equalised KEMAR dummy head data of the MIT Media Lab
// (https://sound.media.mit.edu/resources/KEMAR.html), 44.1kHz, 128 samples per ear:
//
//   "This data is Copyright 1994 by the MIT Media Laboratory. It is provided free with no
//    restrictions on use, provided the authors are cited when the data is used in any research
//    or commercial application."
//   Bill Gardner and Keith Martin, MIT Media Lab Machine Listening Group.
//
// Each ring is one elevation; the azimuths run from 0 (straight ahead) through 90 (right ear) to 180
// (behind). Sources on the left are the mirror image of those on the right.

#include "snd_hrtf.h"
''')
	o.append('const int g_hrtfNumRings = %d;' % len(elevs))
	o.append('const short g_hrtfRingElevation[%d] = { %s };' % (len(elevs), ', '.join(str(e) for e in elevs)))
	counts = [len(rings[e]) for e in elevs]
	offs = [sum(counts[:i]) for i in range(len(counts))]
	o.append('const short g_hrtfRingCount[%d] = { %s };' % (len(elevs), ', '.join(str(c) for c in counts)))
	o.append('const short g_hrtfRingStart[%d] = { %s };' % (len(elevs), ', '.join(str(c) for c in offs)))
	total = sum(counts)
	azs, data = [], []
	for e in elevs:
		for az, f in sorted(rings[e]):
			azs.append(az); L, R = load(f); data.append((L, R))
	o.append('const int g_hrtfNumResponses = %d;' % total)
	o.append('const short g_hrtfAzimuth[%d] = {' % total)
	for i in range(0, total, 24): o.append('\t' + ', '.join(str(a) for a in azs[i:i+24]) + ',')
	o.append('};')
	o.append('// [response][ear (0 left, 1 right)][sample], for a source on the right')
	o.append('const short g_hrtfResponse[%d][2][%d] = {' % (total, 128))
	for L, R in data:
		o.append('{{' + ','.join(str(x) for x in L) + '},{' + ','.join(str(x) for x in R) + '}},')
	o.append('};')
	open(out, 'w', newline='\n').write('\n'.join(o) + '\n')
	print('wrote', out, total, 'responses')
main()
